
tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
